scrum\ScotchLodge\Entities\Comment:
  type: entity
  repositoryClass: scrum\ScotchLodge\Entities\Repo\CommentRepo
  table: comment  
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  
  oneToOne:
    review_comment:
      targetEntity: CommentReview
      mappedBy: comment
      
    event_comment:
      targetEntity: CommentEvent
      mappedBy: comment
      
    parent_comment:
      targetEntity: Comment
      joinColumn:
        name: comment_id
        referencedColumnName: id              
        
  oneToMany:
    comment_likes:
      targetEntity: CommentLike
      mappedBy: comment
        
  manyToOne:
    user:
      targetEntity: User
      inversedBy: comments
      joinColumn: 
        name: user_id
        referencedColumnName: id  
        
  fields:
    comment_date:
      type: datetime
    comment: 
      type: text